# Site settings
email: info@bela.io
# TO TEST YOUR BUILD, uncomment this line:
# baseurl: ""
# ... and comment out this line:
baseurl: "http://blog.bela.io"
# IMPORTANT! Before deploying, make sure you change them back so the github url is active. 
future: false
imageurl: "/assets/images/"
paginate: 10
paginate_path: "/blog/page-:num"
google_analytics: "UA-90171977-1"
# This is the image on the about page:
about-image: main.jpg
site-image: belaboard.jpg

# SEO settings
title: Bela Blog
description: A blog about Bela.
url: ""
twitter_username: BelaPlatform
default_img: "assets/images/STEIM/steim-7.jpg"

#Author names
github: "http://www.github.com/"
twitter: "http://www.twitter.com/"  

# images


# Profile settings
# name: 
# profile_img: 
# profile: 
# social:
#   github: 

# Build settings
include: ["_categories", "_authors"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer, youtube]
