source "https://rubygems.org"

group :jekyll_plugins do
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "octopress-autoprefixer"
  gem "youtube"
  gem "jekyll", ">= 3.6.3"
  gem "ffi", ">= 1.9.24"
end
